version: '3'
services:

  lunatech-countries:
    build: ./countries/1.0.1
    image: lunatech:countries_1.0.1
    container_name: lunatech-countries_1.0.1
    networks:
      - lunatech
  lunatech-airports:
    build: ./airports/1.0.1
    image: lunatech:airports_1.0.1
    container_name: lunatech-airports_1.0.1
    networks:
      - lunatech
  lunatech-nginx:
    image: nginx:stable-alpine
    container_name: lunatech-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./devops.lunatech.com.conf:/etc/nginx/conf.d/devops.lunatech.com.conf"
    links:
      - lunatech-countries:countries_backend
      - lunatech-airports:airports_backend
    ports:
      - "8000:80"
    networks:
      - lunatech

networks:
   lunatech:
     external:
       name: lunatech
